"""
discovery.py — Fast DDS Discovery Server configuration.

Sets up a Discovery Server process and generates the required environment
variable exports and XML profile files for all connected participants.
"""

from __future__ import annotations

import os
import platform
import shutil
import socket
import subprocess
import sys
import textwrap
import time
from pathlib import Path
from typing import Optional

from .platform_utils import EnvironmentInfo, _run, get_primary_ip
from . import ui


# DDS Discovery Server default port
DISCOVERY_SERVER_PORT = 11811

# Directory where we store generated configs
CONFIG_DIR = Path.home() / ".ros2_network_fixer"


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------

def _discovery_server_xml(server_ip: str, server_port: int) -> str:
    """Generate Fast DDS XML profile for client mode pointing at a server."""
    return textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8" ?>
        <!--
            Fast DDS Discovery Server client profile.
            Generated by ros2_network_fixer.
            Source this config by setting:
              FASTRTPS_DEFAULT_PROFILES_FILE={CONFIG_DIR / "fastdds_client.xml"}
              ROS_DISCOVERY_SERVER={server_ip}:{server_port}
        -->
        <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
          <participant profile_name="discovery_server_client" is_default_profile="true">
            <rtps>
              <builtin>
                <discovery_config>
                  <discoveryProtocol>CLIENT</discoveryProtocol>
                  <discoveryServersList>
                    <RemoteServer prefix="44.53.00.5f.45.50.52.4f.53.49.4d.41">
                      <metatrafficUnicastLocatorList>
                        <locator>
                          <udpv4>
                            <address>{server_ip}</address>
                            <port>{server_port}</port>
                          </udpv4>
                        </locator>
                      </metatrafficUnicastLocatorList>
                    </RemoteServer>
                  </discoveryServersList>
                </discovery_config>
              </builtin>
            </rtps>
          </participant>
        </profiles>
    """)


def _discovery_server_profile_xml(server_port: int) -> str:
    """Generate Fast DDS XML profile for the server itself."""
    return textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8" ?>
        <!--
            Fast DDS Discovery Server profile.
            Generated by ros2_network_fixer.
        -->
        <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
          <participant profile_name="discovery_server" is_default_profile="true">
            <rtps>
              <prefix>44.53.00.5f.45.50.52.4f.53.49.4d.41</prefix>
              <builtin>
                <discovery_config>
                  <discoveryProtocol>SERVER</discoveryProtocol>
                  <metatrafficUnicastLocatorList>
                    <locator>
                      <udpv4>
                        <address>0.0.0.0</address>
                        <port>{server_port}</port>
                      </udpv4>
                    </locator>
                  </metatrafficUnicastLocatorList>
                </discovery_config>
              </builtin>
            </rtps>
          </participant>
        </profiles>
    """)


def _env_export_script(
    server_ip: str,
    server_port: int,
    xml_path: Path,
    os_type: str,
) -> dict[str, str]:
    """Return dict mapping filename → script content for each shell type."""
    env_vars = [
        f'ROS_DISCOVERY_SERVER="{server_ip}:{server_port}"',
        f'FASTRTPS_DEFAULT_PROFILES_FILE="{xml_path}"',
    ]

    bash_lines = [f"export {v}" for v in env_vars]
    fish_lines = [
        f'set -x {v.split("=")[0]} {v.split("=", 1)[1].strip(chr(34))}'
        for v in env_vars
    ]
    win_lines = [
        f'set {v.replace(chr(34), "")}' for v in env_vars
    ]
    ps_lines = [
        f'$env:{v.split("=")[0]} = {v.split("=", 1)[1]}'
        for v in env_vars
    ]

    scripts: dict[str, str] = {}

    scripts["setup_discovery.bash"] = (
        "#!/usr/bin/env bash\n"
        "# Source this file: source setup_discovery.bash\n"
        + "\n".join(bash_lines)
        + "\necho '[ros2_network_fixer] Discovery Server environment set.'\n"
    )

    scripts["setup_discovery.fish"] = (
        "#!/usr/bin/env fish\n"
        "# Source this file: source setup_discovery.fish\n"
        + "\n".join(fish_lines)
        + "\necho '[ros2_network_fixer] Discovery Server environment set.'\n"
    )

    scripts["setup_discovery.bat"] = (
        "@echo off\n"
        "REM Run this file: setup_discovery.bat\n"
        + "\n".join(win_lines)
        + "\necho [ros2_network_fixer] Discovery Server environment set.\n"
    )

    scripts["setup_discovery.ps1"] = (
        "# Run: . .\\setup_discovery.ps1\n"
        + "\n".join(ps_lines)
        + "\nWrite-Host '[ros2_network_fixer] Discovery Server environment set.'\n"
    )

    return scripts


# ---------------------------------------------------------------------------
# Discovery server process management
# ---------------------------------------------------------------------------

def _find_fastdds_server(env: EnvironmentInfo) -> Optional[str]:
    """Locate the fastdds or fastdds-discovery-server binary."""
    candidates = [
        "fastdds",
        "fastdds-discovery-server",
        "discovery-server",
        "fastrtps-discovery-server",
    ]
    for name in candidates:
        path = shutil.which(name)
        if path:
            return path

    # Check ROS 2 install dirs
    if env.ros2_home:
        for subdir in ["lib/fastrtps", "lib/fastdds", "bin"]:
            candidate = env.ros2_home / subdir / "fastdds"
            if candidate.exists():
                return str(candidate)

    # Check common ROS 2 paths
    for distro_dir in Path("/opt/ros").glob("*/lib/fastrtps/fastdds"):
        return str(distro_dir)

    return None


def is_port_free(port: int) -> bool:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.bind(("0.0.0.0", port))
        s.close()
        return True
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def setup_discovery_server(
    env: EnvironmentInfo,
    server_ip: Optional[str] = None,
    server_port: int = DISCOVERY_SERVER_PORT,
    start_server: bool = False,
) -> bool:
    """
    Configure Fast DDS Discovery Server mode.

    Generates XML profiles and shell setup scripts.
    Optionally starts the server process if start_server=True and the
    fastdds binary is available.

    Returns True if configuration files were written successfully.
    """
    ui.section("Discovery Server Setup")

    # Determine server IP
    if server_ip is None:
        server_ip = get_primary_ip(env) or "127.0.0.1"

    ui.info(f"Discovery Server address: {server_ip}:{server_port}")

    # Check port availability
    if not is_port_free(server_port):
        ui.warn(f"Port {server_port} appears to be in use.")
        alt_port = server_port + 1
        ui.info(f"Trying alternate port {alt_port}...")
        if is_port_free(alt_port):
            server_port = alt_port
        else:
            ui.error("Could not find a free DDS server port.")
            return False

    # Create config directory
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    client_xml = CONFIG_DIR / "fastdds_client.xml"
    server_xml = CONFIG_DIR / "fastdds_server.xml"

    # Write XML profiles
    client_xml.write_text(_discovery_server_xml(server_ip, server_port))
    server_xml.write_text(_discovery_server_profile_xml(server_port))
    ui.ok(f"Fast DDS client profile: {client_xml}")
    ui.ok(f"Fast DDS server profile: {server_xml}")

    # Write shell setup scripts
    scripts = _env_export_script(server_ip, server_port, client_xml, env.os_type)
    for filename, content in scripts.items():
        script_path = CONFIG_DIR / filename
        script_path.write_text(content)
    ui.ok(f"Setup scripts written to: {CONFIG_DIR}")

    # Print instructions
    ui.section("How to Activate Discovery Server Mode")
    ui.info("Run the appropriate script for your shell BEFORE launching ROS 2 nodes:")
    ui.nl()

    ui.detail("Bash / Zsh:")
    ui.cmd_block(f"source {CONFIG_DIR / 'setup_discovery.bash'}")

    ui.detail("Fish:")
    ui.cmd_block(f"source {CONFIG_DIR / 'setup_discovery.fish'}")

    ui.detail("Windows Command Prompt:")
    ui.cmd_block(str(CONFIG_DIR / "setup_discovery.bat"))

    ui.detail("Windows PowerShell:")
    ui.cmd_block(f". '{CONFIG_DIR / 'setup_discovery.ps1'}'")

    ui.info("Every machine / container that should communicate must source this script.")
    ui.info(f"The server IP ({server_ip}) must be reachable from all participants.")

    # Optionally start the server
    if start_server:
        _start_server_process(env, server_xml, server_ip, server_port)

    # Print the raw env vars for quick manual use
    ui.section("Manual Environment Variables")
    ui.info("Alternatively, set these variables manually before running ros2:")
    ui.code_block([
        f"ROS_DISCOVERY_SERVER={server_ip}:{server_port}",
        f"FASTRTPS_DEFAULT_PROFILES_FILE={client_xml}",
    ], label="env vars")

    return True


def _start_server_process(
    env: EnvironmentInfo,
    server_xml: Path,
    server_ip: str,
    server_port: int,
) -> None:
    """Attempt to launch fastdds discovery server as a background process."""
    fastdds = _find_fastdds_server(env)

    if not fastdds:
        ui.warn("fastdds binary not found — cannot auto-start discovery server.")
        ui.info("Start it manually with:")
        ui.cmd_block(f"fastdds discovery -i 0 -l {server_ip} -p {server_port}")
        ui.info("Or use the ros2 daemon approach:")
        ui.cmd_block("ros2 daemon start")
        return

    ui.step(f"Starting Fast DDS Discovery Server on {server_ip}:{server_port} ...")

    cmd = [fastdds, "discovery", "-i", "0", "-l", server_ip, "-p", str(server_port)]

    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        time.sleep(1.5)

        if proc.poll() is None:
            ui.ok(f"Discovery Server running (PID {proc.pid})")
            # Save PID for later
            (CONFIG_DIR / "server.pid").write_text(str(proc.pid))
        else:
            ui.error("Discovery Server process exited immediately.")
            ui.info(f"Try running manually: {' '.join(cmd)}")
    except Exception as e:
        ui.error(f"Failed to start Discovery Server: {e}")
        ui.info(f"Try running manually: {' '.join(cmd)}")


def stop_discovery_server() -> None:
    """Stop a previously started discovery server."""
    pid_file = CONFIG_DIR / "server.pid"
    if not pid_file.exists():
        ui.warn("No discovery server PID file found.")
        return
    try:
        pid = int(pid_file.read_text().strip())
        if platform.system() == "Windows":
            subprocess.run(["taskkill", "/PID", str(pid), "/F"],
                           capture_output=True)
        else:
            os.kill(pid, 15)  # SIGTERM
        pid_file.unlink()
        ui.ok(f"Discovery Server (PID {pid}) stopped.")
    except Exception as e:
        ui.error(f"Could not stop server: {e}")


def show_discovery_status() -> None:
    """Show current discovery server environment variable status."""
    ds = os.environ.get("ROS_DISCOVERY_SERVER", "")
    fp = os.environ.get("FASTRTPS_DEFAULT_PROFILES_FILE", "")

    if ds:
        ui.ok(f"ROS_DISCOVERY_SERVER = {ds}")
    else:
        ui.warn("ROS_DISCOVERY_SERVER is not set.")

    if fp:
        ui.ok(f"FASTRTPS_DEFAULT_PROFILES_FILE = {fp}")
        if not os.path.isfile(fp):
            ui.warn(f"  … but the file does not exist: {fp}")
    else:
        ui.warn("FASTRTPS_DEFAULT_PROFILES_FILE is not set.")
