"""
domain_id.py — ROS 2 Domain ID management.

ROS_DOMAIN_ID isolates groups of nodes from each other on the same network.
The default (0) causes collisions in shared labs, classrooms, and offices.
Valid range: 0–101 (ports above 101 conflict with OS ephemeral ports on some
systems; 232 is the absolute DDS max but 101 is the safe practical ceiling).

This module:
  - Detects the current domain ID and whether conflicts are likely
  - Suggests a deterministic ID based on hostname or username
  - Generates env-export scripts with the chosen ID
  - Integrates domain ID into all other generated setup scripts
"""

from __future__ import annotations

import hashlib
import os
import re
import shutil
import socket
from pathlib import Path
from typing import Optional

from .platform_utils import EnvironmentInfo, _run
from . import ui


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CONFIG_DIR = Path.home() / ".ros2_network_fixer"

# Safe practical ceiling — avoids colliding with OS ephemeral port ranges
DOMAIN_ID_MIN = 0
DOMAIN_ID_MAX = 101
DOMAIN_ID_DEFAULT = 0


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

def get_current_domain_id() -> int:
    """Return the active ROS_DOMAIN_ID (default 0 if unset)."""
    raw = os.environ.get("ROS_DOMAIN_ID", "0")
    try:
        val = int(raw)
        if DOMAIN_ID_MIN <= val <= DOMAIN_ID_MAX:
            return val
    except ValueError:
        pass
    return DOMAIN_ID_DEFAULT


def is_default_domain() -> bool:
    return os.environ.get("ROS_DOMAIN_ID", "0") == "0"


def suggest_domain_id(env: EnvironmentInfo) -> int:
    """
    Suggest a deterministic, collision-avoiding domain ID.

    Strategy: hash hostname + username, map into 1–101.
    This gives a stable ID per machine that any teammate can reproduce.
    Domain 0 is intentionally avoided so the suggestion differs from default.
    """
    seed = env.hostname + os.environ.get("USER", os.environ.get("USERNAME", "user"))
    digest = int(hashlib.sha256(seed.encode()).hexdigest(), 16)
    # Map into 1–101 (skip 0 so it's visually distinct from the default)
    return (digest % DOMAIN_ID_MAX) + 1


def check_domain_id_conflicts(env: EnvironmentInfo) -> dict:
    """
    Check for potential domain ID conflict situations.
    Returns a dict with keys: current_id, is_default, conflict_risk, suggestion.
    """
    current = get_current_domain_id()
    default = is_default_domain()
    suggestion = suggest_domain_id(env)

    # Conflict risk heuristics
    risk = "low"
    risk_reasons: list[str] = []

    if default:
        # Check if we're in a shared environment
        if env.in_docker:
            risk = "high"
            risk_reasons.append("Docker containers sharing domain 0 will collide")
        elif _looks_like_shared_network(env):
            risk = "medium"
            risk_reasons.append(
                "Multiple non-loopback interfaces detected — likely a shared or lab network"
            )
        else:
            risk = "low"
            risk_reasons.append("Domain 0 is fine for single-machine / isolated setups")

    return {
        "current_id":   current,
        "is_default":   default,
        "conflict_risk": risk,
        "risk_reasons": risk_reasons,
        "suggestion":   suggestion,
    }


def _looks_like_shared_network(env: EnvironmentInfo) -> bool:
    """Heuristic: multiple non-loopback IPs suggests a lab/office scenario."""
    non_lo = [i for i in env.interfaces if not i.is_loopback]
    return len(non_lo) >= 2


# ---------------------------------------------------------------------------
# Script generation
# ---------------------------------------------------------------------------

def _domain_id_env_scripts(domain_id: int) -> dict[str, str]:
    """Generate shell scripts that export ROS_DOMAIN_ID."""
    note = f"# ROS_DOMAIN_ID={domain_id} — generated by ros2_network_fixer\n"
    return {
        "setup_domain.bash": (
            "#!/usr/bin/env bash\n"
            + note
            + f'export ROS_DOMAIN_ID={domain_id}\n'
            + "echo \"[ros2_network_fixer] ROS_DOMAIN_ID set to $ROS_DOMAIN_ID\"\n"
        ),
        "setup_domain.fish": (
            "#!/usr/bin/env fish\n"
            + note
            + f"set -x ROS_DOMAIN_ID {domain_id}\n"
            + f"echo '[ros2_network_fixer] ROS_DOMAIN_ID set to {domain_id}'\n"
        ),
        "setup_domain.bat": (
            "@echo off\n"
            + "REM " + note
            + f"set ROS_DOMAIN_ID={domain_id}\n"
            + f"echo [ros2_network_fixer] ROS_DOMAIN_ID set to {domain_id}\n"
        ),
        "setup_domain.ps1": (
            "# Run: . .\\setup_domain.ps1\n"
            + "# " + note
            + f'$env:ROS_DOMAIN_ID = "{domain_id}"\n'
            + f"Write-Host '[ros2_network_fixer] ROS_DOMAIN_ID set to {domain_id}'\n"
        ),
    }


# ---------------------------------------------------------------------------
# Diagnostic check (imported by diagnostics.py)
# ---------------------------------------------------------------------------

def check_domain_id(env: EnvironmentInfo) -> list:
    """Return CheckResult list for domain ID status."""
    from .diagnostics import CheckResult

    status = check_domain_id_conflicts(env)
    results = []

    current = status["current_id"]
    risk    = status["conflict_risk"]

    if not status["is_default"] and risk == "low":
        results.append(CheckResult(
            name="ROS_DOMAIN_ID",
            passed=True,
            message=f"Domain ID {current} is set (non-default — good).",
        ))
    elif status["is_default"] and risk == "high":
        results.append(CheckResult(
            name="ROS_DOMAIN_ID",
            passed=False,
            message=f"Domain ID is 0 (default) — HIGH collision risk.",
            detail="; ".join(status["risk_reasons"]),
            fix_hint=f"Run '--fix domain-id' to set a unique ID (suggested: {status['suggestion']}).",
        ))
    elif status["is_default"] and risk == "medium":
        results.append(CheckResult(
            name="ROS_DOMAIN_ID",
            passed=False,
            message=f"Domain ID is 0 (default) — possible collision on shared network.",
            detail="; ".join(status["risk_reasons"]),
            fix_hint=f"Run '--fix domain-id' to set a unique ID (suggested: {status['suggestion']}).",
        ))
    else:
        results.append(CheckResult(
            name="ROS_DOMAIN_ID",
            passed=True,
            message=f"Domain ID {current} (default). Fine for isolated single-machine use.",
        ))

    return results


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def setup_domain_id(
    env: EnvironmentInfo,
    domain_id: Optional[int] = None,
    auto_apply: bool = False,
) -> bool:
    """
    Set up ROS_DOMAIN_ID and generate environment scripts.

    If domain_id is None, suggests one and (in interactive mode) asks the user.
    """
    ui.section("ROS Domain ID Configuration")

    status = check_domain_id_conflicts(env)
    current = status["current_id"]
    suggested = status["suggestion"]

    ui.kv("Current ROS_DOMAIN_ID", str(current),
          ok_val=not status["is_default"])
    ui.kv("Conflict risk", status["conflict_risk"],
          ok_val=status["conflict_risk"] == "low")
    for reason in status["risk_reasons"]:
        ui.detail(reason)
    ui.nl()

    # Determine target ID
    if domain_id is None:
        if auto_apply:
            domain_id = suggested
            ui.info(f"Auto-selecting domain ID: {domain_id} (hash of hostname+user)")
        else:
            ui.info(f"Suggested domain ID for this machine: {suggested}")
            ui.detail("(Deterministic hash of hostname + username — stable across sessions)")
            raw = ui.prompt(
                f"Enter domain ID to use [{DOMAIN_ID_MIN}–{DOMAIN_ID_MAX}]",
                default=str(suggested),
            )
            try:
                domain_id = int(raw)
                if not (DOMAIN_ID_MIN <= domain_id <= DOMAIN_ID_MAX):
                    ui.warn(f"ID {domain_id} is out of safe range. Using {suggested}.")
                    domain_id = suggested
            except ValueError:
                ui.warn(f"Invalid input. Using suggested ID: {suggested}.")
                domain_id = suggested

    # Write scripts
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    scripts = _domain_id_env_scripts(domain_id)
    for fname, content in scripts.items():
        (CONFIG_DIR / fname).write_text(content)

    ui.ok(f"Domain ID {domain_id} — setup scripts written to {CONFIG_DIR}")

    ui.section("Activate Domain ID")
    ui.info("Source the appropriate script before starting ROS 2 nodes:")
    ui.detail("Bash / Zsh:")
    ui.cmd_block(f"source {CONFIG_DIR / 'setup_domain.bash'}")
    ui.detail("Fish:")
    ui.cmd_block(f"source {CONFIG_DIR / 'setup_domain.fish'}")
    ui.detail("Windows CMD:")
    ui.cmd_block(str(CONFIG_DIR / "setup_domain.bat"))
    ui.detail("Windows PowerShell:")
    ui.cmd_block(f". '{CONFIG_DIR / 'setup_domain.ps1'}'")

    ui.section("Important")
    ui.warn(f"ALL nodes that should communicate must use the same domain ID ({domain_id}).")
    ui.info("Nodes on different domain IDs are completely invisible to each other.")
    ui.info(f"Valid range: {DOMAIN_ID_MIN}–{DOMAIN_ID_MAX}  |  Default: 0")

    return True
