"""
multihost.py — Multi-machine ROS 2 setup wizard.

Guides users through configuring ROS 2 communication across multiple
physical or virtual machines: robots, dev laptops, Raspberry Pis,
simulation servers, etc.

Approach: Discovery Server is the most reliable cross-machine strategy,
so that's what we configure. Each remote participant gets a ready-to-use
setup script with the correct server address pre-filled.

This module does NOT assume SSH access or any specific network topology.
It generates configuration that users copy/deploy themselves.
"""

from __future__ import annotations

import re
import socket
from pathlib import Path
from typing import Optional

from .platform_utils import EnvironmentInfo, _run, get_primary_ip
from .discovery import DISCOVERY_SERVER_PORT, _discovery_server_xml, _discovery_server_profile_xml
from . import ui


CONFIG_DIR = Path.home() / ".ros2_network_fixer"
MULTIHOST_DIR = CONFIG_DIR / "multihost"


# ---------------------------------------------------------------------------
# Host representation
# ---------------------------------------------------------------------------

class RemoteHost:
    def __init__(self, name: str, ip: str, role: str = "client"):
        self.name = name           # human label, e.g. "robot1" or "laptop"
        self.ip   = ip             # IP address
        self.role = role           # "server" | "client"

    def __repr__(self) -> str:
        return f"{self.name} ({self.ip}) [{self.role}]"


# ---------------------------------------------------------------------------
# Connectivity helpers
# ---------------------------------------------------------------------------

def _ping(ip: str, count: int = 1, timeout: int = 2) -> bool:
    """Return True if the IP responds to ping."""
    import platform
    flag = "-n" if platform.system().lower() == "windows" else "-c"
    rc, _, _ = _run(["ping", flag, str(count), "-W", str(timeout), ip], timeout=timeout + 2)
    return rc == 0


def _check_port_open(ip: str, port: int, timeout: float = 2.0) -> bool:
    """Return True if TCP port is open on remote host."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        result = s.connect_ex((ip, port))
        s.close()
        return result == 0
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Config generation for remote hosts
# ---------------------------------------------------------------------------

def _host_setup_scripts(
    host: RemoteHost,
    server_ip: str,
    server_port: int,
    domain_id: int,
    client_xml_path: Path,
) -> dict[str, str]:
    """Generate all-in-one setup scripts for a remote host."""
    env_vars = {
        "ROS_DOMAIN_ID":                    str(domain_id),
        "ROS_DISCOVERY_SERVER":             f"{server_ip}:{server_port}",
        "FASTRTPS_DEFAULT_PROFILES_FILE":   str(client_xml_path),
    }

    header = (
        f"# ros2_network_fixer — setup for host: {host.name} ({host.ip})\n"
        f"# Discovery Server: {server_ip}:{server_port}\n"
        f"# Domain ID: {domain_id}\n"
    )

    bash = "#!/usr/bin/env bash\n" + header
    bash += "\n".join(f'export {k}="{v}"' for k, v in env_vars.items())
    bash += f"\necho '[ros2_network_fixer] {host.name} environment ready.'\n"

    fish = "#!/usr/bin/env fish\n" + header
    fish += "\n".join(f"set -x {k} {v}" for k, v in env_vars.items())
    fish += f"\necho '[ros2_network_fixer] {host.name} environment ready.'\n"

    bat = "@echo off\n" + "REM " + header.replace("\n", "\nREM ")
    bat += "\n".join(f"set {k}={v}" for k, v in env_vars.items())
    bat += f"\necho [ros2_network_fixer] {host.name} environment ready.\n"

    ps1 = "# " + header.replace("\n", "\n# ")
    ps1 += "\n".join(f'$env:{k} = "{v}"' for k, v in env_vars.items())
    ps1 += f"\nWrite-Host '[ros2_network_fixer] {host.name} environment ready.'\n"

    return {
        f"{host.name}_setup.bash": bash,
        f"{host.name}_setup.fish": fish,
        f"{host.name}_setup.bat":  bat,
        f"{host.name}_setup.ps1":  ps1,
    }


def _deployment_readme(
    server_host: RemoteHost,
    clients: list[RemoteHost],
    server_port: int,
    domain_id: int,
    output_dir: Path,
) -> str:
    """Generate a README that explains how to deploy the generated configs."""
    client_lines = "\n".join(
        f"  - {h.name} ({h.ip}): copy {h.name}_setup.bash and source it"
        for h in clients
    )
    return f"""# Multi-Machine ROS 2 Setup
Generated by ros2_network_fixer.

## Network Topology
  Discovery Server: {server_host.name} ({server_host.ip}:{server_port})
  Domain ID: {domain_id}
  Clients:
{client_lines}

## Deployment Steps

### 1. On the Discovery Server machine ({server_host.name})
Copy and source the server setup script, then start the server:

    source {output_dir}/{server_host.name}_setup.bash
    fastdds discovery -i 0 -l {server_host.ip} -p {server_port}

Or use the ros2 discovery server command:

    ros2 run fastrtps fastdds_discovery -i 0 -p {server_port}

### 2. On each client machine
Copy the appropriate setup script to the machine and source it:

    # On each client (copy the file first):
    source <hostname>_setup.bash   # Linux/macOS
    . .<hostname>_setup.ps1        # Windows PowerShell

### 3. Verify connectivity
On any client, run:

    ros2 node list
    ros2 topic list

You should see nodes running on other machines.

## Firewall Requirements
The following ports must be open (UDP) on the server machine:
  - {server_port}  (Discovery Server)
  - 7400-7500     (RTPS participant ports)

## Troubleshooting
- Ensure all machines can ping each other: ping {server_host.ip}
- Verify the Discovery Server port is reachable from clients
- All machines MUST source their setup script before launching nodes
- All machines MUST use the same ROS_DOMAIN_ID ({domain_id})
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def setup_multihost(
    env: EnvironmentInfo,
    server_ip: Optional[str] = None,
    server_port: int = DISCOVERY_SERVER_PORT,
    domain_id: int = 0,
    hosts: Optional[list[dict]] = None,
    auto_apply: bool = False,
) -> bool:
    """
    Interactive multi-machine setup wizard.

    Guides the user through specifying their network topology and generates
    per-host setup scripts, a shared Fast DDS XML profile, and a README.
    """
    ui.section("Multi-Machine Setup Wizard")
    ui.info("This wizard configures ROS 2 communication across multiple machines.")
    ui.info("It uses Discovery Server mode — the most reliable cross-machine strategy.")
    ui.nl()

    # ── Step 1: Server IP ─────────────────────────────────────────────────
    ui.step("Step 1 — Discovery Server Location")
    auto_ip = get_primary_ip(env) or "127.0.0.1"

    if server_ip:
        ui.info(f"Server IP (provided): {server_ip}")
    elif auto_apply:
        server_ip = auto_ip
        ui.info(f"Server IP (auto-detected): {server_ip}")
    else:
        ui.info("The Discovery Server should run on a machine reachable by all participants.")
        ui.info("This is typically your dev laptop or a dedicated server node — NOT the robot.")
        server_ip = ui.prompt(
            "Enter the IP address of the machine that will run the Discovery Server",
            default=auto_ip,
        )

    # ── Step 2: Domain ID ─────────────────────────────────────────────────
    ui.step("Step 2 — ROS Domain ID")
    if auto_apply:
        ui.info(f"Using domain ID: {domain_id}")
    else:
        raw = ui.prompt("Enter ROS_DOMAIN_ID for all machines (0–101)", default=str(domain_id))
        try:
            domain_id = max(0, min(101, int(raw)))
        except ValueError:
            domain_id = 0
        ui.info(f"Domain ID: {domain_id}")

    # ── Step 3: Define hosts ──────────────────────────────────────────────
    ui.step("Step 3 — Define Participating Machines")

    all_hosts: list[RemoteHost] = []

    if hosts:
        # Provided programmatically
        for h in hosts:
            role = h.get("role", "client")
            all_hosts.append(RemoteHost(h["name"], h["ip"], role))
    elif auto_apply:
        # Just add this machine as server
        hostname = env.hostname or "server"
        all_hosts.append(RemoteHost(hostname, server_ip, "server"))
    else:
        ui.info("Add each machine that will participate in this ROS 2 network.")
        ui.info("Press Enter with an empty name when done.")
        ui.nl()

        # Add server machine
        server_name = ui.prompt("Name for the server machine", default=env.hostname or "server")
        all_hosts.append(RemoteHost(server_name, server_ip, "server"))

        # Add client machines
        idx = 1
        while True:
            ui.nl()
            name = ui.prompt(f"Client machine {idx} name (Enter to finish)", default="")
            if not name:
                break
            ip = ui.prompt(f"IP address for '{name}'", default="")
            if not ip or not re.match(r"\d+\.\d+\.\d+\.\d+", ip):
                ui.warn("Invalid IP — skipping this host.")
                continue
            all_hosts.append(RemoteHost(name, ip, "client"))
            idx += 1

    if not all_hosts:
        ui.warn("No hosts defined. Exiting multi-machine setup.")
        return False

    # ── Step 4: Connectivity check ────────────────────────────────────────
    ui.step("Step 4 — Connectivity Check")
    for host in all_hosts:
        if host.ip in ("127.0.0.1", "localhost", server_ip) and host.role == "server":
            ui.ok(f"  {host.name} ({host.ip}) — local (skipping ping)")
            continue
        reachable = _ping(host.ip)
        if reachable:
            ui.ok(f"  {host.name} ({host.ip}) — reachable")
        else:
            ui.warn(f"  {host.name} ({host.ip}) — ping failed (may be blocked; continuing)")

    # ── Step 5: Generate configs ──────────────────────────────────────────
    ui.step("Step 5 — Generating Configuration Files")
    MULTIHOST_DIR.mkdir(parents=True, exist_ok=True)

    # Shared Fast DDS client XML
    client_xml_content = _discovery_server_xml(server_ip, server_port)
    client_xml_path = MULTIHOST_DIR / "fastdds_client.xml"
    client_xml_path.write_text(client_xml_content)
    ui.ok(f"Fast DDS client profile: {client_xml_path}")

    # Server Fast DDS XML
    server_xml_content = _discovery_server_profile_xml(server_port)
    server_xml_path = MULTIHOST_DIR / "fastdds_server.xml"
    server_xml_path.write_text(server_xml_content)
    ui.ok(f"Fast DDS server profile: {server_xml_path}")

    # Per-host setup scripts
    server_host = next((h for h in all_hosts if h.role == "server"), all_hosts[0])
    clients = [h for h in all_hosts if h.role == "client"]

    for host in all_hosts:
        scripts = _host_setup_scripts(host, server_ip, server_port, domain_id, client_xml_path)
        for fname, content in scripts.items():
            (MULTIHOST_DIR / fname).write_text(content)
    ui.ok(f"Per-host setup scripts written to: {MULTIHOST_DIR}")

    # README
    readme = _deployment_readme(server_host, clients, server_port, domain_id, MULTIHOST_DIR)
    (MULTIHOST_DIR / "README.md").write_text(readme)
    ui.ok(f"Deployment guide: {MULTIHOST_DIR / 'README.md'}")

    # ── Summary ───────────────────────────────────────────────────────────
    ui.section("Multi-Machine Setup Complete")
    ui.info(f"All files written to: {MULTIHOST_DIR}")
    ui.nl()
    ui.info("Deployment summary:")
    for host in all_hosts:
        ui.detail(f"  {host.name} ({host.ip}) [{host.role}]")
        ui.detail(f"    → copy {host.name}_setup.bash (or .fish/.bat/.ps1)")
        if host.role == "server":
            ui.detail(f"    → run: fastdds discovery -i 0 -l {server_ip} -p {server_port}")
    ui.nl()
    ui.info(f"Read {MULTIHOST_DIR}/README.md for full deployment instructions.")

    return True


def test_peer_connectivity(
    env: EnvironmentInfo,
    peer_ip: str,
    server_port: int = DISCOVERY_SERVER_PORT,
) -> bool:
    """
    Test connectivity to a remote Discovery Server or ROS 2 peer.
    Returns True if the peer appears reachable.
    """
    ui.section(f"Peer Connectivity Test — {peer_ip}")

    # ICMP ping
    ping_ok = _ping(peer_ip)
    if ping_ok:
        ui.ok(f"ICMP ping to {peer_ip} succeeded.")
    else:
        ui.warn(f"ICMP ping to {peer_ip} failed (may be blocked by firewall).")

    # UDP port check (TCP as proxy — Discovery Server also binds TCP in some builds)
    port_ok = _check_port_open(peer_ip, server_port)
    if port_ok:
        ui.ok(f"Port {server_port}/TCP open on {peer_ip}.")
    else:
        ui.warn(f"Port {server_port}/TCP closed or filtered on {peer_ip}.")
        ui.detail("Note: UDP connectivity cannot be verified with a simple socket connect.")
        ui.detail(f"Ensure UDP port {server_port} is open in the remote firewall.")

    # DDS port range spot-check
    dds_ok = _check_port_open(peer_ip, 7400)
    if dds_ok:
        ui.ok(f"DDS port 7400/TCP accessible on {peer_ip}.")
    else:
        ui.warn(f"DDS port 7400 closed on {peer_ip} — remote firewall may block DDS.")

    ui.nl()
    overall = ping_ok or port_ok
    if overall:
        ui.ok(f"Peer {peer_ip} appears reachable. Discovery Server should work.")
    else:
        ui.error(f"Peer {peer_ip} is not reachable.")
        ui.info("Check: network routing, firewall rules on both machines, VPN configuration.")

    return overall
