"""
security.py — SROS2 and DDS-Security configuration for ROS 2.

Handles:
  - Detection of current security posture (env vars, keystore presence)
  - SROS2 keystore creation via `ros2 security` CLI
  - Fast DDS security XML profile generation (encryption + signing)
  - Per-node permission and governance document generation
  - Environment variable setup scripts for all shells
  - Security diagnostic checks

DDS-Security standard defines five security plugins:
  1. Authentication  — verifies node identity via X.509 certificates
  2. Access Control  — enforces topic publish/subscribe permissions
  3. Cryptographic   — encrypts RTPS messages (AES-128-GCM or AES-256-GCM)
  4. Logging         — optional audit trail
  5. Data Tagging    — optional data classification labels

SROS2 configures plugins 1-3 by default.  This module enables all three
and generates the minimal set of policy files needed to get a working
secure ROS 2 system.

Reference:
  https://docs.ros.org/en/jazzy/Tutorials/Advanced/Security/Introducing-ros2-security.html
  https://fast-dds.docs.eprosima.com/en/latest/fastdds/security/security.html
"""

from __future__ import annotations

import os
import shutil
import textwrap
from pathlib import Path
from typing import Optional

from .platform_utils import EnvironmentInfo, _run
from . import ui


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CONFIG_DIR = Path.home() / ".ros2_network_fixer"
DEFAULT_KEYSTORE = Path.home() / ".ros2" / "keystore"

# ROS 2 security environment variables
_SEC_ENV_VARS = {
    "ROS_SECURITY_ENABLE":   "true",
    "ROS_SECURITY_STRATEGY": "Enforce",   # Enforce | Permissive | Disabled
    "ROS_SECURITY_KEYSTORE": str(DEFAULT_KEYSTORE),
}

# Strategies and what they mean
STRATEGIES = {
    "Enforce":    "Nodes without valid certificates are refused (production setting).",
    "Permissive": "Nodes without certificates are allowed but logged (transition/dev setting).",
    "Disabled":   "Security is off — same as not setting ROS_SECURITY_ENABLE.",
}


# ---------------------------------------------------------------------------
# XML templates
# ---------------------------------------------------------------------------

def _fastdds_security_xml(keystore: Path) -> str:
    """
    Fast DDS XML profile that enables all three DDS-Security plugins:
    authentication, access-control, and cryptography.

    The paths embedded here point at the files that SROS2 generates
    inside the keystore for each node.  At runtime these are resolved
    relative to $ROS_SECURITY_KEYSTORE/<enclave_path>.
    """
    return textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8" ?>
        <!--
            Fast DDS Security Profile
            Generated by ros2_network_fixer.

            Enables DDS-Security authentication, access-control, and
            cryptographic plugins for all participants in this process.

            Activate by setting:
              FASTRTPS_DEFAULT_PROFILES_FILE={CONFIG_DIR / "fastdds_security.xml"}
              ROS_SECURITY_ENABLE=true
              ROS_SECURITY_STRATEGY=Enforce
              ROS_SECURITY_KEYSTORE={keystore}
        -->
        <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
          <transport_descriptors>
            <!-- Require TLS for all network traffic when using TCP transport.
                 For UDP (default RTPS), DDS-Security handles encryption at
                 the RTPS layer — no transport-level change is needed. -->
          </transport_descriptors>

          <participant profile_name="secure_participant" is_default_profile="true">
            <rtps>
              <propertiesPolicy>
                <properties>

                  <!-- ── Authentication plugin ───────────────────────────── -->
                  <!-- Verifies node identity using X.509 certificates.       -->
                  <property>
                    <name>dds.sec.auth.plugin</name>
                    <value>builtin.PKI-DH</value>
                  </property>
                  <property>
                    <name>dds.sec.auth.builtin.PKI-DH.identity_ca</name>
                    <value>file:{keystore}/public/ca.cert.pem</value>
                  </property>
                  <property>
                    <name>dds.sec.auth.builtin.PKI-DH.identity_certificate</name>
                    <value>file:$(ROS_SECURITY_KEYSTORE)/$(ROS_SECURITY_ENCLAVE_OVERRIDE)/cert.pem</value>
                  </property>
                  <property>
                    <name>dds.sec.auth.builtin.PKI-DH.private_key</name>
                    <value>file:$(ROS_SECURITY_KEYSTORE)/$(ROS_SECURITY_ENCLAVE_OVERRIDE)/key.pem</value>
                  </property>
                  <property>
                    <name>dds.sec.auth.builtin.PKI-DH.password</name>
                    <value></value>
                  </property>

                  <!-- ── Access Control plugin ───────────────────────────── -->
                  <!-- Enforces topic-level publish/subscribe permissions.    -->
                  <property>
                    <name>dds.sec.access.plugin</name>
                    <value>builtin.Access-Permissions</value>
                  </property>
                  <property>
                    <name>dds.sec.access.builtin.Access-Permissions.permissions_ca</name>
                    <value>file:{keystore}/public/ca.cert.pem</value>
                  </property>
                  <property>
                    <name>dds.sec.access.builtin.Access-Permissions.governance</name>
                    <value>file:{keystore}/public/governance.p7s</value>
                  </property>
                  <property>
                    <name>dds.sec.access.builtin.Access-Permissions.permissions</name>
                    <value>file:$(ROS_SECURITY_KEYSTORE)/$(ROS_SECURITY_ENCLAVE_OVERRIDE)/permissions.p7s</value>
                  </property>

                  <!-- ── Cryptographic plugin ────────────────────────────── -->
                  <!-- Encrypts RTPS submessages and payloads (AES-128-GCM). -->
                  <property>
                    <name>dds.sec.crypto.plugin</name>
                    <value>builtin.AES-GCM-GMAC</value>
                  </property>

                  <!-- Enable rtps-level protection (whole RTPS message) -->
                  <property>
                    <name>rtps.participant.rtps_protection_kind</name>
                    <value>ENCRYPT</value>
                  </property>

                </properties>
              </propertiesPolicy>
            </rtps>
          </participant>
        </profiles>
    """)


def _governance_xml() -> str:
    """
    Governance document: domain-wide security rules.

    Sets:
      - allow_unauthenticated_participants = FALSE  (no unsigned nodes)
      - enable_join_access_control = TRUE           (enforce permissions)
      - rtps_protection_kind = ENCRYPT              (encrypt discovery traffic)
      - metadata_protection_kind = ENCRYPT          (encrypt DDS metadata)
      - data_protection_kind = ENCRYPT              (encrypt user data)
    """
    return textwrap.dedent("""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!--
            DDS-Security Governance Document
            Generated by ros2_network_fixer.

            Domain-wide security policy. Signed by the CA and placed at:
              <keystore>/public/governance.p7s  (signed)
              <keystore>/public/governance.xml  (unsigned source)
        -->
        <dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_governance.xsd">
          <domain_access_rules>
            <domain_rule>
              <!-- Apply to all DDS domains -->
              <domains>
                <id_range>
                  <min>0</min>
                  <max>232</max>
                </id_range>
              </domains>

              <!-- Reject any participant that cannot authenticate -->
              <allow_unauthenticated_participants>false</allow_unauthenticated_participants>

              <!-- Enforce the per-node permissions documents -->
              <enable_join_access_control>true</enable_join_access_control>

              <!-- Encrypt RTPS discovery traffic -->
              <rtps_protection_kind>ENCRYPT</rtps_protection_kind>

              <topic_access_rules>
                <!-- Default rule: encrypt everything -->
                <topic_rule>
                  <topic_expression>*</topic_expression>
                  <enable_discovery_protection>true</enable_discovery_protection>
                  <enable_liveliness_protection>true</enable_liveliness_protection>
                  <enable_read_access_control>true</enable_read_access_control>
                  <enable_write_access_control>true</enable_write_access_control>
                  <metadata_protection_kind>ENCRYPT</metadata_protection_kind>
                  <data_protection_kind>ENCRYPT</data_protection_kind>
                </topic_rule>
              </topic_access_rules>

            </domain_rule>
          </domain_access_rules>
        </dds>
    """)


def _permissions_xml(enclave: str, topics_publish: list[str], topics_subscribe: list[str]) -> str:
    """
    Per-node (enclave) permissions document.

    Grants the named enclave permission to publish and subscribe to
    the specified topic lists within any DDS domain.

    'enclave' should be the ROS 2 enclave path, e.g. '/talker_node'.
    Pass ['*'] for topics_publish / topics_subscribe to allow all topics
    (appropriate for dev/testing; restrict in production).
    """
    pub_allow = "\n".join(
        f"              <topics><topic>{t}</topic></topics>" for t in topics_publish
    )
    sub_allow = "\n".join(
        f"              <topics><topic>{t}</topic></topics>" for t in topics_subscribe
    )

    return textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!--
            DDS-Security Permissions Document for enclave: {enclave}
            Generated by ros2_network_fixer.

            Signed and placed at:
              <keystore>{enclave}/permissions.p7s  (signed)
              <keystore>{enclave}/permissions.xml  (unsigned source)
        -->
        <dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd">
          <permissions>
            <grant name="{enclave.strip('/')}_grant">

              <!-- Subject name must match the CN in the node's certificate -->
              <subject_name>/C=US/ST=CA/O=ros2_network_fixer/CN={enclave.strip('/')}</subject_name>

              <validity>
                <!-- Valid from now; adjust for production deployments -->
                <not_before>2024-01-01T00:00:00</not_before>
                <not_after>2034-01-01T00:00:00</not_after>
              </validity>

              <allow_rule>
                <domains><id_range><min>0</min><max>232</max></id_range></domains>

                <publish>
{pub_allow}
                </publish>

                <subscribe>
{sub_allow}
                </subscribe>

              </allow_rule>

              <!-- Deny everything not explicitly allowed above -->
              <default>DENY</default>

            </grant>
          </permissions>
        </dds>
    """)


# ---------------------------------------------------------------------------
# Shell setup scripts
# ---------------------------------------------------------------------------

def _security_env_scripts(keystore: Path, strategy: str) -> dict[str, str]:
    """Generate per-shell setup scripts that export security env vars."""
    env_vars = {
        "ROS_SECURITY_ENABLE":   "true",
        "ROS_SECURITY_STRATEGY": strategy,
        "ROS_SECURITY_KEYSTORE": str(keystore),
    }

    bash_lines   = [f'export {k}="{v}"' for k, v in env_vars.items()]
    fish_lines   = [f"set -x {k} {v}"   for k, v in env_vars.items()]
    win_lines    = [f"set {k}={v}"       for k, v in env_vars.items()]
    ps_lines     = [f'$env:{k} = "{v}"' for k, v in env_vars.items()]

    note = (
        "# Source this file in every terminal before running ROS 2 nodes.\n"
        "# Each node must also have a keystore entry — see:\n"
        "#   ros2 security create_enclave <keystore> <enclave_path>\n"
    )

    return {
        "setup_security.bash": (
            "#!/usr/bin/env bash\n"
            + note
            + "\n".join(bash_lines)
            + "\necho '[ros2_network_fixer] SROS2 security environment set.'\n"
        ),
        "setup_security.fish": (
            "#!/usr/bin/env fish\n"
            + note.replace("#", "#")
            + "\n".join(fish_lines)
            + "\necho '[ros2_network_fixer] SROS2 security environment set.'\n"
        ),
        "setup_security.bat": (
            "@echo off\n"
            + "REM " + note.replace("\n", "\nREM ").rstrip("REM ")
            + "\n".join(win_lines)
            + "\necho [ros2_network_fixer] SROS2 security environment set.\n"
        ),
        "setup_security.ps1": (
            "# Source: . .\\setup_security.ps1\n"
            + note.replace("#", "#")
            + "\n".join(ps_lines)
            + "\nWrite-Host '[ros2_network_fixer] SROS2 security environment set.'\n"
        ),
    }


# ---------------------------------------------------------------------------
# Keystore operations
# ---------------------------------------------------------------------------

def _sros2_available() -> bool:
    """Return True if ros2 security subcommand is reachable."""
    rc, out, _ = _run(["ros2", "security", "--help"], timeout=6)
    return rc == 0


def _create_keystore(keystore: Path) -> bool:
    """Run `ros2 security create_keystore <path>`."""
    keystore.parent.mkdir(parents=True, exist_ok=True)
    rc, out, err = _run(["ros2", "security", "create_keystore", str(keystore)], timeout=30)
    if rc == 0:
        ui.ok(f"Keystore created: {keystore}")
        return True
    ui.error(f"ros2 security create_keystore failed (exit {rc})")
    if err:
        ui.detail(err)
    return False


def _create_enclave(keystore: Path, enclave: str) -> bool:
    """Run `ros2 security create_enclave <keystore> <enclave>`."""
    rc, out, err = _run(
        ["ros2", "security", "create_enclave", str(keystore), enclave],
        timeout=30,
    )
    if rc == 0:
        ui.ok(f"Enclave created: {enclave}")
        return True
    ui.error(f"ros2 security create_enclave failed for {enclave}")
    if err:
        ui.detail(err)
    return False


def _sign_governance(keystore: Path) -> bool:
    """
    Write governance.xml and sign it with the CA key.
    Returns True even if signing is skipped (unsigned .xml still useful
    for users who want to sign manually or use permissive mode).
    """
    gov_xml_path = keystore / "public" / "governance.xml"
    gov_xml_path.parent.mkdir(parents=True, exist_ok=True)
    gov_xml_path.write_text(_governance_xml())
    ui.ok(f"Governance XML written: {gov_xml_path}")

    # Try to sign via ros2 security sign_governance
    rc, _, err = _run(
        ["ros2", "security", "sign_governance",
         str(keystore), str(gov_xml_path)],
        timeout=15,
    )
    if rc == 0:
        ui.ok("Governance document signed (governance.p7s)")
        return True

    # Older distros use openssl directly
    ca_cert = keystore / "public" / "ca.cert.pem"
    ca_key  = keystore / "private" / "ca.key.pem"
    out_p7s = keystore / "public" / "governance.p7s"

    if ca_cert.exists() and ca_key.exists() and shutil.which("openssl"):
        rc2, _, err2 = _run([
            "openssl", "smime", "-sign",
            "-in",    str(gov_xml_path),
            "-text",
            "-out",   str(out_p7s),
            "-signer", str(ca_cert),
            "-inkey",  str(ca_key),
            "-noattr", "-nodetach",
        ], timeout=15)
        if rc2 == 0:
            ui.ok("Governance document signed via openssl (governance.p7s)")
            return True
        ui.warn("openssl signing failed — governance.xml written but not signed.")
        if err2:
            ui.detail(err2)
    else:
        ui.warn("Could not sign governance document automatically.")

    ui.info("Sign manually with:")
    ui.cmd_block(
        f"openssl smime -sign -in {gov_xml_path} -text "
        f"-out {keystore}/public/governance.p7s "
        f"-signer {keystore}/public/ca.cert.pem "
        f"-inkey {keystore}/private/ca.key.pem -noattr -nodetach"
    )
    return True  # Non-fatal — unsigned XML is still written


# ---------------------------------------------------------------------------
# Diagnostic checks
# ---------------------------------------------------------------------------

def check_security_posture(env: EnvironmentInfo) -> list:
    """
    Return a list of CheckResult-compatible dicts describing the current
    security posture.  Imported by diagnostics.py.
    """
    from .diagnostics import CheckResult

    results = []

    # 1. ROS_SECURITY_ENABLE
    sec_enable = os.environ.get("ROS_SECURITY_ENABLE", "").lower()
    if sec_enable == "true":
        results.append(CheckResult(
            name="ROS_SECURITY_ENABLE",
            passed=True,
            message="DDS security is enabled (ROS_SECURITY_ENABLE=true).",
        ))
    else:
        results.append(CheckResult(
            name="ROS_SECURITY_ENABLE",
            passed=False,
            message="DDS security is OFF — traffic is unencrypted and unauthenticated.",
            fix_hint="Run '--fix security' to set up SROS2 encryption and authentication.",
        ))

    # 2. ROS_SECURITY_STRATEGY
    strategy = os.environ.get("ROS_SECURITY_STRATEGY", "")
    if strategy in ("Enforce", "Permissive"):
        results.append(CheckResult(
            name="ROS_SECURITY_STRATEGY",
            passed=strategy == "Enforce",
            message=f"Security strategy: {strategy}. {STRATEGIES.get(strategy, '')}",
        ))
    elif sec_enable == "true":
        results.append(CheckResult(
            name="ROS_SECURITY_STRATEGY",
            passed=False,
            message="ROS_SECURITY_STRATEGY is not set (defaults to Permissive).",
            fix_hint="Set ROS_SECURITY_STRATEGY=Enforce to block unsigned nodes.",
        ))

    # 3. ROS_SECURITY_KEYSTORE
    keystore_path = os.environ.get("ROS_SECURITY_KEYSTORE", "")
    if keystore_path:
        ks = Path(keystore_path)
        if ks.exists():
            results.append(CheckResult(
                name="ROS_SECURITY_KEYSTORE",
                passed=True,
                message=f"Keystore found: {ks}",
            ))
        else:
            results.append(CheckResult(
                name="ROS_SECURITY_KEYSTORE",
                passed=False,
                message=f"Keystore path set but directory does not exist: {ks}",
                fix_hint="Run '--fix security' to create the keystore.",
            ))
    elif sec_enable == "true":
        results.append(CheckResult(
            name="ROS_SECURITY_KEYSTORE",
            passed=False,
            message="ROS_SECURITY_KEYSTORE is not set.",
            fix_hint="Run '--fix security' to configure the keystore path.",
        ))

    # 4. FASTRTPS_DEFAULT_PROFILES_FILE pointing at security profile
    profiles_file = os.environ.get("FASTRTPS_DEFAULT_PROFILES_FILE", "")
    security_xml = CONFIG_DIR / "fastdds_security.xml"
    if profiles_file and "security" in profiles_file.lower():
        results.append(CheckResult(
            name="Fast DDS security profile",
            passed=True,
            message=f"Security XML profile active: {profiles_file}",
        ))
    elif security_xml.exists():
        results.append(CheckResult(
            name="Fast DDS security profile",
            passed=False,
            message=f"Security XML profile exists but is not active.",
            fix_hint=f"Source setup_security.bash (or .ps1/.bat) from {CONFIG_DIR}",
        ))

    return results


# ---------------------------------------------------------------------------
# Public setup API
# ---------------------------------------------------------------------------

def setup_security(
    env: EnvironmentInfo,
    keystore: Optional[Path] = None,
    strategy: str = "Enforce",
    enclaves: Optional[list[str]] = None,
    auto_apply: bool = False,
) -> bool:
    """
    Configure SROS2 / DDS-Security for ROS 2.

    Steps:
      1. Create keystore (if it doesn't exist) via ros2 security CLI
      2. Write governance.xml and sign it
      3. Write Fast DDS security XML profile
      4. Create any requested enclaves (nodes)
      5. Write per-enclave permissions.xml files
      6. Generate shell setup scripts

    Parameters
    ----------
    env       : detected environment
    keystore  : path for the keystore (default: ~/.ros2/keystore)
    strategy  : Enforce | Permissive  (default: Enforce)
    enclaves  : list of enclave paths to create, e.g. ["/talker", "/listener"]
                Pass None or [] to skip enclave creation
    auto_apply: skip interactive prompts
    """
    ui.section("SROS2 / DDS-Security Setup")

    if keystore is None:
        keystore = DEFAULT_KEYSTORE

    if strategy not in ("Enforce", "Permissive"):
        ui.warn(f"Unknown strategy '{strategy}' — defaulting to Enforce.")
        strategy = "Enforce"

    ui.info(f"Keystore path:  {keystore}")
    ui.info(f"Strategy:       {strategy} — {STRATEGIES[strategy]}")
    ui.nl()

    # ── Prerequisite check ────────────────────────────────────────────────
    has_ros2_security = _sros2_available()
    if not has_ros2_security:
        ui.warn("ros2 security CLI not found — ROS 2 may not be sourced.")
        ui.warn("Generating config files anyway; keystore creation will be skipped.")
        ui.info("Run 'source /opt/ros/<distro>/setup.bash' then re-run this command.")

    # ── Step 1: Keystore ─────────────────────────────────────────────────
    ui.step("Keystore")
    keystore_ok = False
    if keystore.exists():
        ui.ok(f"Keystore already exists: {keystore}")
        keystore_ok = True
    elif has_ros2_security:
        keystore_ok = _create_keystore(keystore)
    else:
        keystore.mkdir(parents=True, exist_ok=True)
        (keystore / "public").mkdir(exist_ok=True)
        (keystore / "private").mkdir(exist_ok=True)
        ui.warn(f"Created empty keystore directory: {keystore}")
        ui.info("Populate it with: ros2 security create_keystore " + str(keystore))

    # ── Step 2: Governance ────────────────────────────────────────────────
    ui.step("Governance document")
    _sign_governance(keystore)

    # ── Step 3: Fast DDS security XML profile ────────────────────────────
    ui.step("Fast DDS security XML profile")
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    sec_xml_path = CONFIG_DIR / "fastdds_security.xml"
    sec_xml_path.write_text(_fastdds_security_xml(keystore))
    ui.ok(f"Security profile written: {sec_xml_path}")

    # ── Step 4 & 5: Enclaves + permissions ───────────────────────────────
    if enclaves:
        ui.step(f"Creating {len(enclaves)} enclave(s)")
        for enclave in enclaves:
            if not enclave.startswith("/"):
                enclave = "/" + enclave
            if has_ros2_security and keystore_ok:
                _create_enclave(keystore, enclave)
            # Write a permissions.xml even if ros2 CLI unavailable
            enc_dir = keystore / enclave.lstrip("/")
            enc_dir.mkdir(parents=True, exist_ok=True)
            perm_xml = enc_dir / "permissions.xml"
            perm_xml.write_text(_permissions_xml(enclave, ["*"], ["*"]))
            ui.ok(f"  Permissions XML: {perm_xml}")
            ui.detail("  Topic wildcards allow all topics — restrict in production.")
    else:
        ui.info("No enclaves specified. Add nodes with:")
        ui.cmd_block(f"ros2 security create_enclave {keystore} /your_node_name")

    # ── Step 6: Shell scripts ─────────────────────────────────────────────
    ui.step("Shell setup scripts")
    scripts = _security_env_scripts(keystore, strategy)
    for filename, content in scripts.items():
        (CONFIG_DIR / filename).write_text(content)
    ui.ok(f"Setup scripts written to: {CONFIG_DIR}")

    # ── Instructions ──────────────────────────────────────────────────────
    _print_activation_instructions(keystore, strategy, sec_xml_path)

    return True


def _print_activation_instructions(
    keystore: Path, strategy: str, sec_xml_path: Path
) -> None:
    ui.section("How to Enable Security")

    ui.info("Source the security setup script in every terminal before running nodes:")
    ui.nl()
    ui.detail("Bash / Zsh:")
    ui.cmd_block(f"source {CONFIG_DIR / 'setup_security.bash'}")
    ui.detail("Fish:")
    ui.cmd_block(f"source {CONFIG_DIR / 'setup_security.fish'}")
    ui.detail("Windows CMD:")
    ui.cmd_block(str(CONFIG_DIR / "setup_security.bat"))
    ui.detail("Windows PowerShell:")
    ui.cmd_block(f". '{CONFIG_DIR / 'setup_security.ps1'}'")

    ui.section("Manual Environment Variables")
    ui.code_block([
        f"ROS_SECURITY_ENABLE=true",
        f"ROS_SECURITY_STRATEGY={strategy}",
        f"ROS_SECURITY_KEYSTORE={keystore}",
        f"FASTRTPS_DEFAULT_PROFILES_FILE={sec_xml_path}",
    ], label="env vars")

    ui.section("Adding Nodes to the Keystore")
    ui.info("Each ROS 2 node needs its own enclave entry. Example:")
    ui.cmd_block(f"ros2 security create_enclave {keystore} /my_robot/sensor_node")
    ui.cmd_block(f"ros2 security create_enclave {keystore} /my_robot/controller_node")

    if strategy == "Enforce":
        ui.warn("Strategy is ENFORCE — nodes without a keystore entry will be REFUSED.")
        ui.info("Switch to Permissive during development: edit setup_security.bash")
        ui.detail("ROS_SECURITY_STRATEGY=Permissive  ← allows unsigned nodes but logs them")

    ui.section("Verifying Security is Active")
    ui.info("After sourcing the script and launching nodes, verify with:")
    ui.cmd_block("ros2 security list_enclaves " + str(keystore))
    ui.cmd_block("ros2 node list  # nodes should appear if certs are valid")

    ui.section("Security Model Summary")
    ui.detail("Authentication : X.509 PKI — nodes prove identity with signed certificates")
    ui.detail("Access Control : permissions.xml — per-node topic allow/deny lists")
    ui.detail("Encryption     : AES-128-GCM   — all RTPS traffic encrypted end-to-end")
    ui.detail("Scope          : All topics (*) allowed by default — restrict for production")


def print_security_status() -> None:
    """Print current SROS2 environment variable status."""
    ui.section("Security Status")
    enabled  = os.environ.get("ROS_SECURITY_ENABLE",   "false").lower() == "true"
    strategy = os.environ.get("ROS_SECURITY_STRATEGY", "(not set)")
    keystore = os.environ.get("ROS_SECURITY_KEYSTORE",  "(not set)")

    ui.kv("ROS_SECURITY_ENABLE",   "true" if enabled else "false (insecure default)", ok_val=enabled)
    ui.kv("ROS_SECURITY_STRATEGY", strategy,   ok_val=strategy == "Enforce")
    ui.kv("ROS_SECURITY_KEYSTORE", keystore,   ok_val=keystore != "(not set)")

    if not enabled:
        ui.warn("Traffic is unencrypted. Run '--fix security' to enable SROS2.")